# Generated by Django 5.1.6 on 2025-02-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код подтверждения'),
        ),
    ]
